NEW

diff --git a/start b/start
--- a/start
+++ b/start
@@ -38,7 +38,7 @@ print_rainbow() {
     echo -e "$reset"
 }
 cek_status() {
-    pm2 status | grep -q botvpn && echo "aktif" || echo "nonaktif"
+    pm2 status | grep -q sellvpn && echo "aktif" || echo "nonaktif"
 }
 
 setup_bot() {
@@ -53,23 +53,23 @@ setup_bot() {
         echo -e "${green}Node.js is already installed, skipping...${neutral}"
     fi
 
-    if [ ! -f /root/BotVPN-POTATO/app.js ]; then
-        git clone https://github.com/arivpnstores/BotVPN-POTATO.git /root/BotVPN-POTATO
+    if [ ! -f /root/BotVPN/app.js ]; then
+        git clone https://github.com/AutoFTbot/BotVPN.git /root/BotVPN
     fi
 
-    if ! npm list --prefix /root/BotVPN-POTATO express telegraf axios moment sqlite3 >/dev/null 2>&1; then
-        npm install --prefix /root/BotVPN-POTATO sqlite3 express crypto telegraf axios dotenv
+    if ! npm list --prefix /root/BotVPN express telegraf axios moment sqlite3 >/dev/null 2>&1; then
+        npm install --prefix /root/BotVPN sqlite3 express crypto telegraf axios dotenv
     fi
 
-    if [ -n "$(ls -A /root/BotVPN-POTATO)" ]; then
-        chmod +x /root/BotVPN-POTATO/*
+    if [ -n "$(ls -A /root/BotVPN)" ]; then
+        chmod +x /root/BotVPN/*
     fi
 }
 
 server_app() {
     clear
     echo -e "${orange}─────────────────────────────────────────${neutral}"
-    echo -e "   ${green}.:::. BOT VPN TELEGRAM .:::.   ${neutral}"
+    echo -e "   ${green}.:::. BOT SELLVPN TELEGRAM .:::.   ${neutral}"
     echo -e "${orange}─────────────────────────────────────────${neutral}"
     echo -e "       ${green}•${neutral} server create user"
     echo -e "       ${green}•${neutral} server delete user"
@@ -119,7 +119,7 @@ server_app() {
             echo -e "${red}GROUP ID tidak boleh kosong. Silakan coba lagi.${neutral}"
         fi
     done
-    rm -f /root/BotVPN-POTATO/.vars.json
+    rm -f /root/BotVPN/.vars.json
     echo "{
   \"BOT_TOKEN\": \"$token\",
   \"USER_ID\": \"$adminid\",
@@ -129,9 +129,9 @@ server_app() {
   \"DATA_QRIS\": \"$dataqris\",
   \"MERCHANT_ID\": \"$merchantid\",
   \"API_KEY\": \"$apikey\"
-}" >/root/BotVPN-POTATO/.vars.json
+}" >/root/BotVPN/.vars.json
 
-    pm2 start /root/BotVPN-POTATO/app.js --name botvpn --env production -- --token "$token" --adminid "$adminid" --namastore "$namastore" --dataqris "$dataqris" --merchantid "$merchantid" --apikey "$apikey"
+    pm2 start /root/BotVPN/app.js --name sellvpn --env production -- --token "$token" --adminid "$adminid" --namastore "$namastore" --dataqris "$dataqris" --merchantid "$merchantid" --apikey "$apikey"
     pm2 save
 
     printf "\033[5A\033[0J"
@@ -141,10 +141,10 @@ server_app() {
     echo -e "${green}Type ${bold_white}/start${neutral} or ${bold_white}menu${neutral} in the telegram bot${neutral}"
 }
 
-if [[ ${1} == "botvpn" ]]; then
+if [[ ${1} == "sellvpn" ]]; then
     setup_bot
     server_app
 else
-    echo -e "${red}Invalid command. Use: ${yellow}start botvpn${neutral}"
+    echo -e "${red}Invalid command. Use: ${yellow}start sellvpn${neutral}"
     exit 1
 fi 
